sonar.projectKey=sebastianfuentesavalos_examenuii
sonar.organization=sebastianfuentesavalos

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=examenuii
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=OrderApp/OrderApp.Domain
sonar.tests=OrderApp/OrderApp.Domain.Tests

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Language
sonar.language=cs

# Exclusions for Files
sonar.exclusions=**/bin/**,**/obj/**,**/*.dll

# Exclusions for Duplications
sonar.cpd.exclusions=**/Migrations/**

# Coverage Exclusions
sonar.coverage.exclusions=**/*Tests.cs,**/Program.cs,**/Startup.cs

# Test Coverage
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.cs.vstest.reportsPaths=**/TestResults.xml

# Additional settings
sonar.dotnet.excludeGeneratedCode=true